#端口号
server:
  port: 8081

#数据库配置
spring:
  datasource:
    url: jdbc:mysql://192.168.170.201:3306/sleeve?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root123456@!@#ABx,.ssss1
    driver-class-name: com.mysql.jdbc.Driver
  jpa: #打印SQL一般只有在dev环境开启
    show-sql: true
    properties:
      format_sql: true

